version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:15.9 
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-default_password} 
      POSTGRES_DB: ${DB_NAME:-default_db}                
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5