version: '3.8'   #afecta la conf de postgres

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest  #14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data   # cambio .postgres por .data
