version: '3.8'   #afecta la conf de postgres

services:
  postgres:
    container_name: postgres_db
    image: postgres:13.4  #14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # - ./data:/var/lib/postgresql/data   # cambio .postgres por .data
      - ./postgres_win10:/var/lib/postgresql/data  # Windows 10
      - ./postgres_win11:/var/lib/postgresql/data  # Windows 11
